### PR TITLE
Remove unnecessary workflow for publishing branch

### PR DESCRIPTION
**Pull request by mthaddon**
Motivation described in https://github.com/canonical/operator-workflows/pull/15

### CODE REVIEW

**Review by gtrkiller — DISMISSED** [review]
LGTM

**Review by arturo-seijas — CHANGES_REQUESTED** [review]
Missing changes in the on_push wf: https://github.com/canonical/indico-operator/pull/165/files

**Review by arturo-seijas — DISMISSED** [review]
LGTM

**Review by gtrkiller — DISMISSED** [review]
LGTM

**Review by arturo-seijas — APPROVED** [review]
LGTM

**Review by gtrkiller — APPROVED** [review]
LGTM

**Pull request merged**
