### PR TITLE
add IngressProxyProvides class

### PR DESCRIPTION
**Pull request by gtrkiller**
Add the IngressProxyProvides class for the content-cache-k8s charm to use it.

### CODE REVIEW

**Review by gregory-schiano — DISMISSED** [review]
LGTM

**Comment by gregory-schiano** [comment]
Could be interesting to add integration/unit tests to cover that class ?

**Review by amandahla — APPROVED** [review]
LGTM

**Review by merkata — APPROVED** [review]
Nice!

**Review by merkata — APPROVED** [review]

**Review by amandahla — DISMISSED** [review]

**Review by merkata — APPROVED** [review]

**Review by amandahla — APPROVED** [review]

**Pull request merged**
